# frozen_string_literal: true

# Serves the Swagger UI interactive API documentation page and the
# underlying swagger.json specification generated by Apipie.
class ApiDocsController < ApplicationController
  def index
  end

  def swagger_json
    spec_path = Rails.root.join("public", "apipie_swagger.json")

    unless File.exist?(spec_path)
      render json: {error: "Swagger specification not found. Run 'rake swagger:generate' to create it."}, status: :not_found
      return
    end

    send_file spec_path, type: "application/json", disposition: "inline"
  end
end
